version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    dns:
      - 8.8.8.8

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    container_name: bot
    depends_on:
      - redis
      - webapp
    volumes:
      - ./bot/cache:/bot/cache
    environment:
      - REDIS_HOST=redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    volumes:
      - ./my_api_project:/var/www/html
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./my_api_project:/var/www/html
    depends_on:
      - webappпше
    dns:
      - 8.8.8.8
